spring:
  application:
    name: booquest

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Flyway로 관리하므로 none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # (선택) 외부 프로퍼티 파일을 '있으면' 불러오기
  # 기존 @PropertySource 대체 — 파일 없으면 무시하므로 부팅 실패 없음
  config:
    import: optional:classpath:properties/env.properties

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: ${SERVER_PORT:8080}

# --- AI 서버 설정 ---
ai:
  base-url: ${AI_BASE_URL:http://localhost:8081}
  timeout-ms: ${AI_TIMEOUT_MS:5000}

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace  # 쿼리 파라미터 출력
    com.fasterxml.jackson: DEBUG
    org.springframework.http.converter: DEBUG

kakao:
  api:
    user-info-url: https://kapi.kakao.com/v2/user/me

naver:
  api:
    user-info-url: https://openapi.naver.com/v1/nid/me

apple:
  auth:
    issuer: https://appleid.apple.com
    jwks-uri: https://appleid.apple.com/auth/keys
    audience: com.booquest.app  # 앱의 번들 ID
    client-id: ${APPLE_CLIENT_ID}  # 서비스 ID
    client-secret: ${APPLE_CLIENT_SECRET}
    team-id: ${APPLE_TEAM_ID}  # Apple Developer Team ID
    key-id: ${APPLE_KEY_ID}  # AuthKey_XXXXXX.p8의 키 ID
    private-key: ${APPLE_PRIVATE_KEY}
    revoke-url: https://appleid.apple.com/auth/revoke
    timeout-ms: 4000
    retry:
      max-attempts: 1

oauth:
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}
    unlink-url: https://kapi.kakao.com/v1/user/unlink
    timeout-ms: 4000
    retry:
      max-attempts: 1
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    token-url: https://nid.naver.com/oauth2.0/token
    timeout-ms: 4000
    retry:
      max-attempts: 1

jwt:
  secret: ${JWT_SECRET}
  access-token-ttl-seconds: 3600
  refresh-token-ttl-seconds: 2592000

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
