spring:
  application:
    name: booquest

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Flyway로 관리하므로 none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # (선택) 외부 프로퍼티 파일을 '있으면' 불러오기
  # 기존 @PropertySource 대체 — 파일 없으면 무시하므로 부팅 실패 없음
  config:
    import: optional:classpath:properties/env.properties

  profiles:
    active: dev

server:
  port: ${SERVER_PORT:8080}

# --- AI 서버 설정 ---
ai:
  base-url: ${AI_BASE_URL:http://localhost:8000}
  timeout-ms: ${AI_TIMEOUT_MS:5000}

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace  # 쿼리 파라미터 출력

kakao:
  api:
    user-info-url: https://kapi.kakao.com/v2/user/me

jwt:
  secret: ${JWT_SECRET}
  access-token-ttl-seconds: 3600
  refresh-token-ttl-seconds: 2592000