spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  flyway:
    enabled: false
  datasource:
    url: ""                # 상속/머지 방지
    driver-class-name: ""
    username: ""
    password: ""
  data:
    jpa:
      repositories:
        enabled: false     # (보강) 리포지토리도 비활성화

logging:
  level:
    org.hibernate: WARN

ai:
  base-url: http://localhost:8000
