name: "✨ 기능 추가"
description: "새로운 기능이나 개선 사항을 제안합니다."
title: "[Feature] "
labels: ["feat"]

body:
  - type: markdown
    attributes:
      value: |
        ## 📌 기능 설명  
        어떤 기능을 추가하거나 개선할지 설명해주세요.
  - type: textarea
    id: feature-description
    attributes:
      label: 기능 설명
      description: 새로 제안할 기능의 목적과 내용을 구체적으로 작성해주세요.
      placeholder: 예) 유저 프로필에 이미지 업로드 기능을 추가하고 싶습니다.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## 🛠 예상 작업 내용  
        해야 할 작업을 체크리스트 형태로 작성해주세요.
  - type: textarea
    id: expected-tasks
    attributes:
      label: 예상 작업 내용
      description: 마크다운 체크박스 형식으로 자유롭게 작성하세요.  
      placeholder: |
        - [ ] DB 모델 정의  
        - [ ] API 설계 및 개발  
        - [ ] 프론트엔드 연동  
    validations:
      required: false

  - type: textarea
    id: implementation-idea
    attributes:
      label: 💡 구현 방향 (선택)
      description: 기술 스택, 설계 방향, UI 방식 등 구체적인 계획이 있다면 적어주세요.
      placeholder: 예) React Dropzone 라이브러리 사용 예정
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 🔗 참고 자료 (선택)
      description: 참고할 링크나 이미지 등이 있다면 남겨주세요.
      placeholder: 예) https://github.com/example/project
    validations:
      required: false
